language: bash

sudo: false

addons:
  apt:
    sources:
      - debian-sid    # Grab ShellCheck from the Debian repo
    packages:
      - shellcheck

env:
  global:
    - FIND_SH="find $TRAVIS_BUILD_DIR -name '*.sh' -type f -print0"
    - FIND_JSON="find $TRAVIS_BUILD_DIR -name '*.json' -type f -print0"
    - XARGS="xargs -0 -n1 -I {} -t"

before_install:
  - curl -sO http://stedolan.github.io/jq/download/linux64/jq
  - chmod +x jq
  - jq --version
  - shellcheck --version

before_script:
  - echo $JOB
  - echo $TESTCOMMAND

script:
  - bash -c "$TESTCOMMAND"

jobs:
  include:
    - stage: test
      env:
        - JOB="Shell Script Syntax Verification"
        - TESTCOMMAND="$FIND_SH | $XARGS shellcheck {}"
    - stage: test
      env:
        - JOB="JSON Syntax Verification"
        - TESTCOMMAND="$FIND_JSON | $XARGS jq --exit-status . {} > /dev/null"
    - stage: test
      env:
        - JOB="JSON Lint/Format Verification"
        - TESTCOMMAND="$FIND_JSON | $XARGS bash -c 'cmp {} <(jq --indent 4 -S . {})'"
    - stage: deploy
      if: branch = master AND type = push AND repo = plus3it/spel
      script: skip
      before_deploy:
        - |
          RELEASE_VERSION=$(cat $TRAVIS_BUILD_DIR/.bumpversion.cfg | grep current_version | sed 's/^.*= //' )
          RELEASE_BODY="* [SPEL v$RELEASE_VERSION CHANGELOG](https://github.com/plus3it/spel/blob/$RELEASE_VERSION/CHANGELOG.md)"
          export RELEASE_VERSION RELEASE_BODY
          (set -x; git tag -a $RELEASE_VERSION -m $RELEASE_VERSION)
      deploy:
        provider: releases
        api_key:
          secure: SxBWbiOc8wELixxH+CYzoBHIvqP9Iq85seo4rO3rPfTDld0IWDRSYlLOCXL7fujKAPmNbv1nICX9VPVOyMvjdeUY3RLJ2LIqkEm9fRieuZr8CzbROszmeLHhHl8hD4m8Adkg1QHo+fqNgzvjldPD0YDwbqbFFB5hXzSMu603D6qM/ymyZqCMF/F3DBdYhDN/xu6a32b9vSeochC1YrbucQXXZA8wE/pHmBqHQ0s9gRIkdBP3OgLaWb8wpoNJ8IzTBi7KdAyDs5plqMtjA1n/pUJKZ8WI5S59LMyFDwP2BUwVxQR5LddwGS2UEsFLjmCuB9H9NT7T2nAbbFVrlOmzCgCW6AvMCK3meEwpFsitJv/MYe6XRqkCFrSNPLrdp3Pa4gOX+rQUD7jRwXB4M8Fk12/fJbIdZbjFDsSWN2+zG9MoiNQJPTJs/oyvZsL1Xp/ab1GaggJDiAoVKHPenbDgIKjIYp+uxRPLGGT1/CTzth3D+D6pdgnCaETUFyIZot+OkLzSWj5atyFPQfqnxDiDNmMYKHDjjaYFLHAbLdVjP2RYQHJmdOYXtGrQQ8KEs0IJy2y8LXD+XFOvHwh0zm79+d7G6l18gVymdrYXO09/ctUK/vWPbhYelllurq+kttESMO0srDRe5Kadyh6gdEng1xm2qrX0OAHAl4qVL6tOE4Q=
        name: $RELEASE_VERSION
        tag_name: $RELEASE_VERSION
        body: $RELEASE_BODY
        draft: false
